# Google App Engine / Cloud Run configuration
runtime: nodejs20

# Build configuration
build_env_variables:
  NODE_ENV: production

# Environment variables
env_variables:
  NODE_ENV: production

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 10

# Health check
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2